In [6]:
import pprint 
import numpy as np
np.random.seed(0)
x1= np.random.randint(10,size=6)
x2= np.random.randint(10,size=(3,4))
x3= np.random.randint(10,size=(3,4,5))
print(x1)
pprint.pprint(x2)
pprint.pprint(x3)
print(x3.ndim)
print(x3.shape)
print(x3.size)

[5 0 3 3 7 9]
array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])
array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])
3
(3, 4, 5)
60


In [7]:
x2[0,0]=12
pprint.pprint(x2)

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])


In [15]:
x2[:2, :3]
x2[::-1, ::-1] #Rows,Column
x2_sub=x2[0:2,0:2]
print(x2_sub)
x2_sub[0,0]=99
pprint.pprint(x2)
#Slices are views, not copies. That means that if slices are affected, originals are also affected. 
#For unaffected lists:
x2_copy=x2[:2,:2].copy()
x2_copy[0,0]=12
pprint.pprint(x2_copy)
pprint.pprint(x2)

[[99  5]
 [ 7  6]]
array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])
array([[12,  5],
       [ 7,  6]])
array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])


In [18]:
grid=np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
