In [1]:
import numpy as np
np.array([1,2,3,4,5],dtype="float32")

array([1., 2., 3., 4., 5.], dtype=float32)

In [2]:
print(np.zeros(10,dtype="int"))
print(np.ones((3,5),dtype="int"))
print(np.full((3,5),3.14))
print(np.arange(0, 20, 2))
print(np.linspace(0,1,5))
print(np.random.random((3,3)))
print(np.random.normal(0,1,(3,3))) #0=Mean. 1=Standard Deviation
print(np.random.randint(0,10,(3,3))) #0=Mean. 1=Standard Deviation
print(np.eye(3))

[0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.96459631 0.79919446 0.17014878]
 [0.87674907 0.73162912 0.46738617]
 [0.75981887 0.98353977 0.48215152]]
[[-0.016971    0.60032302 -0.59892725]
 [-0.93410473  0.46082899 -1.22688362]
 [ 1.76884987  1.82684345  0.98403593]]
[[8 5 8]
 [2 1 2]
 [0 5 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
twodim = np.array([np.arange(4),np.arange(4)])
twodim.shape
threedim=np.array([np.array([np.arange(4),np.arange(4),np.arange(4)]),np.array([np.arange(4),np.arange(4),np.arange(4)])])
print(twodim)
print(threedim)

[[0 1 2 3]
 [0 1 2 3]]
[[[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


In [65]:
t=np.dtype('S')
print(t.char)
print(t.str)
print(t.type)

TypeError: data type 't' not understood

In [79]:
record=np.dtype([("name", str,40),("items",int),("price",float)])
print(record)
print(record["name"])
itemz=np.array([('Meaning of life DVD',42,3.14),('Butter',13,2.72)],dtype=record)
print(itemz[1])

[('name', '<U40'), ('items', '<i4'), ('price', '<f8')]
<U40
('Butter', 13, 2.72)


In [4]:
#Slicing
b=np.arange(24).reshape(2,3,4)
print(b)
print(b.shape)
print(b[1,2,0])
print(b[:,0,0])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
20
[ 0 12]


In [5]:
print(b[0])
print(b[0,:,:])
print(b[0],...)
print(b[0,1])
print(b[0,1,0::2])
print(b[...,1])
print(b[:,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] Ellipsis
[4 5 6 7]
[4 6]
[[ 1  5  9]
 [13 17 21]]
[[ 4  5  6  7]
 [16 17 18 19]]


In [6]:
print(b[0,:,1])
print(b[0,:,-1])
print(b[0,::-1,-1])

[1 5 9]
[ 3  7 11]
[11  7  3]


In [10]:
#Matrix Transformations
viewing=b.ravel()
copies=b.flatten()
viewing[-1]=69
copies[0]=69
print(b)
copies.shape=(6,4)
print(copies)
print(copies.transpose())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 69]]]
[[69  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 69]]
[[69  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 69]]


In [18]:
#Stacking Two Dimensional Arrays
a=np.arange(9).reshape(3,3)
b=2*a
print(a)
print(b)
c1=np.hstack((a,b))
c12=np.concatenate((a,b),axis=1)
c2=np.vstack((a,b))
c22=np.concatenate((a,b),axis=0)
c3=np.dstack((a,b))
print(c1)
print(c12)
print(c2)
print(c22)
print(c3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]


In [25]:
#Stacking One Dimensional
oned=np.arange(2)
twoned=2*oned
o1=np.column_stack((oned,twoned))
c13=np.column_stack((a,b))
print(o1)
print(c13)
o2=np.row_stack((oned,twoned))
c23=np.row_stack((a,b))
print(o2)
print(c23)

[[0 0]
 [1 2]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[0 1]
 [0 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [29]:
#Splitting
s1=np.hsplit(c1,3)
s12=np.split(c1,3,axis=1)
print(s1)
print(s12)
s2=np.vsplit(c2,3)
s22=np.split(c2,3,axis=0)
print(s2)
print(s22)
#Dsplitting, divides by columns.

[array([[0, 1],
       [3, 4],
       [6, 7]]), array([[ 2,  0],
       [ 5,  6],
       [ 8, 12]]), array([[ 2,  4],
       [ 8, 10],
       [14, 16]])]
[array([[0, 1],
       [3, 4],
       [6, 7]]), array([[ 2,  0],
       [ 5,  6],
       [ 8, 12]]), array([[ 2,  4],
       [ 8, 10],
       [14, 16]])]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8],
       [0, 2, 4]]), array([[ 6,  8, 10],
       [12, 14, 16]])]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8],
       [0, 2, 4]]), array([[ 6,  8, 10],
       [12, 14, 16]])]


In [39]:
#Dimensions
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.itemsize)
print(b.nbytes)
print(b.T)
b.astype('float64')
b.tolist()


[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
2
(3, 3)
9
4
36
[[ 0  6 12]
 [ 2  8 14]
 [ 4 10 16]]


[[0, 2, 4], [6, 8, 10], [12, 14, 16]]